name: Development Workflow

on:
  workflow_dispatch:
    inputs:
      customer_id:
        description: 'Customer ID'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-west-1'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./${{ github.event.inputs.customer_id }}/dev

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./${{ github.event.inputs.customer_id }}/dev

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./${{ github.event.inputs.customer_id }}/dev

    - name: Print AWS Environment Variables
      run: |
        echo "AWS Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS Secret Access Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        
    - name: Test AWS CLI
      run: aws s3 ls


    
