name: Production Workflow

on:
  workflow_dispatch:
    inputs:
      customer_id:
        description: 'Customer ID'
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest
    name: Terraform Plan and Apply for Production
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./customers/${{ github.event.inputs.customer_id }}/prd

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./customers/${{ github.event.inputs.customer_id }}/prd

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./customers/${{ github.event.inputs.customer_id }}/prd
